<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f17f65c5-ee50-4594-9aae-ac84bb1da53e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
      <Compile Remove="ProviderCatalogService.Tests\**" />
      <Content Remove="ProviderCatalogService.Tests\**" />
      <EmbeddedResource Remove="ProviderCatalogService.Tests\**" />
      <None Remove="ProviderCatalogService.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.30" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.30">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Kafka\Shared.Kafka.csproj" />
  </ItemGroup>

</Project>
